# Generated by Django 6.0.7 on 2026-07-07 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_recurring_transactions_and_spendable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
